### ISSUE TITLE
Check the link of IIEST Shibpur

### ISSUE THREAD

**Issue by ayan-biswas0412** [jadavpur-university-ed-cell/IICJadavpurUniversity#9]
One suggestion for the navbar 
check : https://www.iiests.ac.in/

![image](https://user-images.githubusercontent.com/52851184/78119374-f3bbbb00-7425-11ea-8ff4-2bcb68fe8fb5.png)

Like this in the place of iiest logo we can add our JU logo alongwith IIC logo and in the extreme right side the word (full form of iic ) can be written.

* And the NAVBAR should be open from top to down in case of mobile device .

**Comment by skshahnawaz** [comment]
done. check https://iicju.netlify.com . One small dropdown issue is there. Will fix it later
